"""Field-level encryption helpers for VaxAI Vision.

Strategy
--------
- Primary: Fernet symmetric encryption (cryptography library).
  Key source: ENCRYPTION_KEY env var (32-byte URL-safe base64 value).
- Optional: AWS KMS data-key envelope encryption when KMS_KEY_ARN is set.
  The data-key is generated by KMS, encrypted under the KMS CMK, and the
  plaintext data-key is used locally for Fernet encryption.  Only the
  encrypted data-key is stored alongside the ciphertext.

Usage
-----
    from app.core.encryption import encrypt_field, decrypt_field

    # Encrypt before storing to DB:
    stored_value = encrypt_field("patient-ssn-or-phi")

    # Decrypt after reading from DB:
    plaintext = decrypt_field(stored_value)

If ENCRYPTION_AT_REST_ENABLED is False (default in development) the functions
are transparent pass-throughs so the rest of the code doesn't need to branch.
"""

from __future__ import annotations

import base64
import logging
import os
from functools import lru_cache
from typing import Optional

from app.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


# ── Key loading ────────────────────────────────────────────────────────────────

_FERNET_UNAVAILABLE_MSG = (
    "cryptography package is not installed.  "
    "Run: pip install cryptography"
)

try:
    from cryptography.fernet import Fernet, MultiFernet
    _CRYPTO_AVAILABLE = True
except ImportError:
    _CRYPTO_AVAILABLE = False


@lru_cache(maxsize=1)
def _get_fernet() -> "MultiFernet | None":
    """Build a MultiFernet from ENCRYPTION_KEY (supports key rotation)."""
    if not _CRYPTO_AVAILABLE:
        logger.warning(_FERNET_UNAVAILABLE_MSG)
        return None

    raw = os.environ.get("ENCRYPTION_KEY", "")
    if not raw:
        logger.warning(
            "ENCRYPTION_KEY is not set — field-level encryption is disabled."
        )
        return None

    # Support comma-separated keys for rotation (first key is the current one)
    keys = [k.strip() for k in raw.split(",") if k.strip()]
    fernets = []
    for k in keys:
        try:
            fernets.append(Fernet(k.encode() if isinstance(k, str) else k))
        except Exception as exc:
            logger.error("Invalid ENCRYPTION_KEY value: %s", exc)
    if not fernets:
        return None
    return MultiFernet(fernets)


# ── KMS support (optional) ─────────────────────────────────────────────────────


def _kms_encrypt(plaintext: bytes) -> Optional[tuple[bytes, bytes]]:
    """Generate a KMS data key and encrypt plaintext with it.

    Returns (ciphertext, encrypted_data_key) or None if KMS is unavailable.
    """
    kms_arn = getattr(settings, "KMS_KEY_ARN", None)
    if not kms_arn:
        return None
    try:
        import boto3  # type: ignore

        client = boto3.client("kms")
        resp = client.generate_data_key(KeyId=kms_arn, KeySpec="AES_256")
        plaintext_key: bytes = resp["Plaintext"]
        encrypted_key: bytes = resp["CiphertextBlob"]
        # Derive a Fernet key from the raw AES key (Fernet needs 32 bytes base64url)
        fernet_key = base64.urlsafe_b64encode(plaintext_key[:32])
        f = Fernet(fernet_key)
        return f.encrypt(plaintext), encrypted_key
    except Exception as exc:
        logger.error("KMS encryption failed: %s", exc)
        return None


def _kms_decrypt(ciphertext: bytes, encrypted_data_key: bytes) -> Optional[bytes]:
    """Decrypt a KMS-encrypted data key and use it to decrypt ciphertext."""
    try:
        import boto3  # type: ignore

        client = boto3.client("kms")
        resp = client.decrypt(CiphertextBlob=encrypted_data_key)
        plaintext_key: bytes = resp["Plaintext"]
        fernet_key = base64.urlsafe_b64encode(plaintext_key[:32])
        f = Fernet(fernet_key)
        return f.decrypt(ciphertext)
    except Exception as exc:
        logger.error("KMS decryption failed: %s", exc)
        return None


# ── Public API ─────────────────────────────────────────────────────────────────

# Prefix tags stored in the DB to distinguish plaintext vs. encrypted values
_FERNET_TAG = "enc:fernet:"
_KMS_TAG = "enc:kms:"


def encrypt_field(plaintext: str) -> str:
    """Encrypt a sensitive string field.

    If encryption is disabled or the key is unavailable, returns the original
    string so the application still functions in development.

    Returns a tagged string:
      - "enc:fernet:<base64-ciphertext>"  for local Fernet encryption
      - "enc:kms:<base64(encrypted_key)>:<base64(ciphertext)>"  for KMS
    """
    if not getattr(settings, "ENCRYPTION_AT_REST_ENABLED", False):
        return plaintext

    raw = plaintext.encode("utf-8")

    # Try KMS first if configured
    kms_result = _kms_encrypt(raw)
    if kms_result is not None:
        ciphertext, enc_key = kms_result
        ct_b64 = base64.urlsafe_b64encode(ciphertext).decode()
        key_b64 = base64.urlsafe_b64encode(enc_key).decode()
        return f"{_KMS_TAG}{key_b64}:{ct_b64}"

    # Fall back to local Fernet
    fernet = _get_fernet()
    if fernet is None:
        logger.warning("encrypt_field: no encryption key available — storing plaintext")
        return plaintext
    token = fernet.encrypt(raw)
    return f"{_FERNET_TAG}{token.decode()}"


def decrypt_field(stored_value: str) -> str:
    """Decrypt a previously encrypted field.

    If the value is not tagged (i.e. stored plaintext), returns it unchanged.
    """
    if not stored_value:
        return stored_value

    if stored_value.startswith(_KMS_TAG):
        payload = stored_value[len(_KMS_TAG):]
        key_b64, ct_b64 = payload.split(":", 1)
        enc_key = base64.urlsafe_b64decode(key_b64)
        ciphertext = base64.urlsafe_b64decode(ct_b64)
        plaintext = _kms_decrypt(ciphertext, enc_key)
        if plaintext is None:
            raise ValueError("KMS decryption failed for stored field")
        return plaintext.decode("utf-8")

    if stored_value.startswith(_FERNET_TAG):
        token = stored_value[len(_FERNET_TAG):].encode()
        fernet = _get_fernet()
        if fernet is None:
            raise ValueError("Fernet key unavailable — cannot decrypt field")
        return fernet.decrypt(token).decode("utf-8")

    # Not encrypted (development mode or legacy data)
    return stored_value


def generate_fernet_key() -> str:
    """Generate a new Fernet key suitable for use as ENCRYPTION_KEY."""
    if not _CRYPTO_AVAILABLE:
        raise RuntimeError(_FERNET_UNAVAILABLE_MSG)
    return Fernet.generate_key().decode()
